#!/bin/bash

PROMPT='[bootstrap]'

# Environment 
export PATH_TO_PROJECTS="$HOME/projects"

# Echo utility
echo_prompt () {
  echo "$PROMPT $@"
}

# Initialize
init () {
  echo_prompt "Making a PROJECTS folder in $PATH_TO_PROJECTS"
  mkdir -p "$PATH_TO_PROJECTS"
  echo_prompt "Making a .config directory if it doesn't already exist"
  mkdir -p ~/.config
  echo_prompt "Disabling mpd as a system service, Enabling as user process."
  sudo systemctl disable mpd.service
  sudo systemctl disable mpd.socket
  systemctl --user enable mpd.service
  systemctl --user enable mpd.socket
}

# Install
symlinks () {
  echo_prompt "Installing symlinks for vim, tmux, zsh, mpd, ncmpcpp, newsboat in the .config directory..."
  read -p "$PROMPT Proceed? (Y/n)" -n 1 -r
  echo
  if [[ "$REPLY" =~ ^[Yy]$ ]]
  then
    mkdir -p ~/.config/zsh ~/.config/ncmpcpp ~/.config/mpd ~/.config/kitty ~/.config/newsboat 
    ln -svfn ~/dotfiles/vim/vimrc ~/.vimrc
    ln -svfn ~/dotfiles/zsh/zshenv ~/.zshenv
    ln -svfn ~/dotfiles/tmux/tmux.conf ~/.tmux.conf
    ln -svfn ~/dotfiles/scripts ~/scripts

    ln -svfn ~/dotfiles/xorg/xinitrc ~/.xinitrc

    ln -svfn ~/dotfiles/zsh/zshrc ~/.config/zsh/.zshrc
    ln -svfn ~/dotfiles/zsh/alaisrc ~/.config/aliasrc
    ln -svfn ~/dotfiles/ncmpcpp/config ~/.config/ncmpcpp/config 
    ln -svfn ~/dotfiles/ncmpcpp/bindings ~/.config/ncmpcpp/bindings
    ln -svfn ~/dotfiles/mpd/mpd.conf ~/.config/mpd/mpd.conf
    ln -svfn ~/dotfiles/kitty/kitty.conf ~/.config/kitty/kitty.conf
    ln -svfn ~/dotfiles/kitty/gruvbox_dark.conf ~/.config/kitty/theme.conf
    ln -svfn ~/dotfiles/newsboat ~/.config/newsboat
    echo_prompt "Symlink done"
  else
    echo_prompt "Symlink cancelled"
    return 1
  fi
}

init
symlinks
