#!/bin/bash

PROMPT='[dotfiles bootstrap]'

# Environment 
export PATH_TO_PROJECTS="$HOME/projects"

# Echo utility
echo_prompt () {
  echo "$PROMPT $@"
}

# Initialize
init () {
  echo_prompt "Making a PROJECTS folder in $PATH_TO_PROJECTS if it doesn't already exist"
  mkdir -p "$PATH_TO_PROJECTS"
  echo_prompt "Making a .config directory if it doesn't already exist"
  mkdir -p ~/.config
  # echo_prompt "Disabling mpd as a system service, Enabling as user process."
  # sudo systemctl disable mpd.service
  # sudo systemctl disable mpd.socket
  # systemctl --user enable mpd.service
  # systemctl --user enable mpd.socket
}

# Install
symlinks () {
  echo_prompt "Installing symlinks in respective directories..."
  read -p "$PROMPT Proceed? (Y/n)" -n 1 -r
  echo
  if [[ "$REPLY" =~ ^[Yy]$ ]]
  then
    mkdir -p ~/.config/zsh ~/.config/nvim 
    mkdir -p ~/.config/skhd ~/.config/yabai
    mkdir -p ~/.config/ncmpcpp ~/.config/mpd ~/.config/kitty ~/.config/newsboat
    # vim/nvim
    ln -svfn ~/projects/dotfiles/vim/vimrc ~/.vimrc
    ln -svfn ~/projects/dotfiles/vim/vimrc ~/.config/nvim/init.vim

    # tmux
    ln -svfn ~/projects/dotfiles/tmux/tmux.conf ~/.tmux.conf

    # scripts
    ln -svfn ~/projects/dotfiles/scripts ~/scripts

    # skhd + yabai
    ln -svfn ~/projects/dotfiles/skhd/skhdrc ~/.config/skhd/skhdrc
    ln -svfn ~/projects/dotfiles/yabai/yabairc ~/.config/yabai/yabairc

    # zsh
    ln -svfn ~/projects/dotfiles/zsh/zshenv ~/.zshenv
    ln -svfn ~/projects/dotfiles/zsh/zshrc ~/.config/zsh/.zshrc
    ln -svfn ~/projects/dotfiles/zsh/aliasrc ~/.config/aliasrc

    ln -svfn ~/projects/dotfiles/vim/init.lua ~/.config/nvim/init.lua
    ln -svfn ~/projects/dotfiles/vim/lua ~/.config/nvim/lua

    # Xorg
    # ln -svfn ~/projects/dotfiles/xorg/xbindkeysrc ~/.xbindkeysrc
    # ln -svfn ~/projects/dotfiles/xorg/xinitrc ~/.xinitrc

    # ncmpcpp + mpd
    # ln -svfn ~/projects/dotfiles/ncmpcpp/config ~/.config/ncmpcpp/config 
    # ln -svfn ~/projects/dotfiles/ncmpcpp/bindings ~/.config/ncmpcpp/bindings
    # ln -svfn ~/projects/dotfiles/mpd/mpd.conf ~/.config/mpd/mpd.conf

    # kitty
    ln -svfn ~/projects/dotfiles/kitty/kitty.conf ~/.config/kitty/kitty.conf
    ln -svfn ~/projects/dotfiles/kitty/gruvbox_dark.conf ~/.config/kitty/theme.conf

    # newsboat
    ln -svfn ~/projects/dotfiles/newsboat/config ~/.config/newsboat/config
    ln -svfn ~/projects/dotfiles/newsboat/urls ~/.config/newsboat/urls

    # taskwarrior
    ln -svfn ~/projects/dotfiles/task/taskrc ~/.taskrc

    echo_prompt "Symlink done"
  else
    echo_prompt "Symlink cancelled"
    return 1
  fi
}

init
symlinks
