"       ____  __
"      / / / / /    Jason Hong
" __  / / /_/ /     https://github.com/jasonhong0810
"/ /_/ / __  /      :) 
"\____/_/ /_/   

" syntax
syntax on

" disable default vim startup
set shortmess+=I

" show line numbers and relative line numbers
set rnu
set nu

" show status line
set laststatus=2

" backspace over anything
set backspace=indent,eol,start

" allows hidden buffers with unsaved changes
set hidden

" makes search case-insensitive, search becomes case-sensitive if it contains any capital letters
set ignorecase
set smartcase

" search as you type
set incsearch

" enable mouse support
set mouse+=a

" disable bell noise
set noerrorbells visualbell t_vb=

" highlight search
set hls

" extend history
set history=8192

" open split pane right and bottom
set splitbelow
set splitright

" tabstops
set tabstop=2 shiftwidth=2 expandtab

" plugins
" vim-plug automatic installation
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugsrc')

" general
Plug 'justinmk/vim-sneak'
Plug 'junegunn/fzf'

" gui
Plug 'preservim/nerdtree'
Plug 'itchyny/lightline.vim'

" syntactic language
Plug 'w0rp/ale'

" plugin configuration
let NERDTreeShowHidden=1

call plug#end()
