-- local lsp_installer = require("nvim-lsp-installer")
--
-- local all_servs = { "bashls", "pyright", "gopls", "sumneko_lua", "jdtls", "ccls", "rust_analyzer", "tsserver"}
--
-- lsp_installer.settings({
--   ensure_installed = all_servs,
--   automatic_installation = false,
--   ui = {
--       icons = {
--           server_installed = "✓",
--           server_pending = "➜",
--           server_uninstalled = "✗"
--       }
--   }
-- })




-- lsp_installer.setup{}
-- require("lspconfig").sumneko_lua.setup{}
-- for _, lsp in pairs (all_servs) do
--   if lsp == 'sumneko_lua' then
--     require ('lspconfig')[lsp].setup {
--       settings = {
--         Lua = {
--           diagnostics = {
--             globals = { 'vim' }
--           }
--         }
--       }
--     }
--   else require ('lspconfig')[lsp].setup {
--     on_attach = on_attach,
--     flags = {
--       debounce_text_changes = 150,
--     }
--   }
--   end
-- end
--
