#!/bin/sh

xbindkeys
setxkbmap -option caps:escape
# xcompmgr -c &
picom --no-fading-openclose --experimental-backends &
# feh --no-fehbg --bg-scale ~/personal/wallpapers/normal/circlemountain.png
dwmblocks &
exec dwm
