#!/bin/sh

# tmux environment startup script
# Last modified: 12/30/2020

# Session variables
SESSION="dev-env"
LIVE=$(tmux ls | grep $SESSION)

# If a session doesn't exist
if [ "$LIVE" = "" ]
then
  # Start
  tmux new-session -d -s $SESSION

  # Rename window
  tmux rename-window -t 0 'Main'

  # Setup main window
  tmux send-keys "vim" Enter
  tmux split-window
  tmux split-window -h

  # Set up initial programs
  tmux select-pane -t 1
  tmux send-keys "htop" Enter
  
  tmux select-pane -t 2

  # Cursor on left-most
  tmux select-pane -t 0
fi

tmux attach-session -t $SESSION:0
