#!/bin/sh

# fedora upgrade

# Backup Package list #
rpm -qa | sort > ~/Documents/pkglist.txt

# Install from previously saved list #
# sudo dnf install $(cat pkglist.txt)

# Remove orphaned packages #
sudo dnf autoremove

# Remove package cache #
# sudo dnf clean all

# Final update
sudo dnf upgrade
