#!/bin/sh

# updates

# backup package list
rpm -qa | sort > ~/Documents/pkglist.txt

# install from previously saved list
# sudo dnf install $(cat pkglist.txt)

# clean orphaned pkgs
sudo dnf autoremove

# clean pkg cache
# sudo dnf clean all

# update
sudo dnf upgrade

# flatpaks
flatpak update
