#!/bin/sh
#
# ufetch-macos - tiny system info for macos

## INFO

# user is already defined
host="$(hostname -s)"
os="$(sw_vers -productName) $(sw_vers -productVersion)"
kernel="$(uname -sr)"
uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
shell="$(basename "${SHELL}")"

ui="$(basename "${ui}")"

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
lc="${reset}${bold}"                # labels
nc="${reset}${bold}"                # user and hostname
ic="${reset}"                       # info
c0="${reset}"                       # first color

## OUTPUT

cat <<EOF
${c0}          _${reset}
${c0}         (/     ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}    .---__--.   ${lc}os:        ${ic}${os}${reset}
${c0}   /         \  ${lc}kernel:    ${ic}${kernel}${reset}
${c0}  |         /   ${lc}uptime:    ${ic}${uptime}${reset}
${c0}  |         \\_ ${lc}shell:     ${ic}${shell}${reset}
${c0}   \         /  ${lc}ui:        ${ic}${ui}${reset}
${c0}    \`._.-._.\`   

EOF
