#!/bin/sh

alias sync-git="rsync --uvrP --delete-after ~/Documents/JH/projects/git/cgitrc root@jasonhong.xyz:/etc/cgitrc"
alias sync-site="rsync --uvrP --delete-after --exclude '.git' ~/Documents/JH/projects/website/ root@jasonhong.xyz:/var/www/jasonhong"
alias tmux-kill="tmux kill-session"
alias ls="ls --color"
alias vim="nvim"
