#!/bin/sh

# This file is run by zsh on login/startup to set basic environment variables

# Defaults:
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER="firefox"

# ~/ Clean-up
export ZDOTDIR="$HOME/.config/zsh"
export LESSHISTFILE="-"
. "$HOME/.cargo/env"
