# color
autoload -U colors && colors

# TERM
export TERM=xterm-256color

# Prompt
PS1="%B%{$fg[black]%}%{$fg[green]%}λ %{$fg[magenta]%}%~%{$fg[black]%}%{$reset_color%} >%b "
#PS1="%B%{$fg[black]%}%{$fg[white]%} %{$fg[yellow]%}%~%{$fg[black]%}%{$reset_color%} >%b "

# vimkeys
bindkey -v

# editor
export EDITOR='nvim'
export VISUAL='nvim'

# history
HISTFILE=~/.config/zsh/.zsh_history
HISTSIZE=1000
SAVEHIST=1000

# compinit
autoload -Uz compinit
zstyle ':completion:*' menu select
zstyle :compinstall filename '/home/jason/.zshrc'
zmodload zsh/complist
compinit

# Include hidden files in autocomplete:
_comp_options+=(globdots)

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

export KEYTIMEOUT=1

# Change cursor shape for different vi modes.
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'

  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select

# Use beam shape cursor on startup.
echo -ne '\e[5 q'

# Use beam shape cursor for each new prompt.
preexec() { echo -ne '\e[5 q' ;}

# add scripts to path
export PATH="$HOME/scripts/bar:$HOME/scripts:$HOME/.local/bin:$PATH"

# startup
export PF_COLOR=1
export HOSTNAME="rhea"

# source aliasrc
source ~/.config/aliasrc

# source pip
export PATH="/Users/jasonhong/Library/Python/3.9/bin:$PATH"
export PATH="/Users/jasonhong/go/bin:$PATH"

# source jdtls
# export JAVA_HOME="/opt/homebrew/Cellar/openjdk/18.0.2.1_1/libexec/openjdk.jdk/Contents/Home"
# export JAVA_HOME="/opt/homebrew/Cellar/openjdk/19/libexec/openjdk.jdk/Contents/Home"
export JAVA_HOME="/opt/homebrew/Cellar/openjdk/19/libexec/openjdk.jdk/Contents/Home"

# source ruby
source $HOMEBREW_PREFIX/opt/chruby/share/chruby/chruby.sh
source $HOMEBREW_PREFIX/opt/chruby/share/chruby/auto.sh
chruby ruby-3.1.2

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/jasonhong/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/jasonhong/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/jasonhong/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/jasonhong/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

pfetch

# Load zsh-syntax-highlighting; should be last.
# source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# bun completions
[ -s "/Users/jasonhong/.bun/_bun" ] && source "/Users/jasonhong/.bun/_bun"
